{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "claude-toolkit.fullname" . }}-claude
  labels:
    {{- include "claude-toolkit.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLAUDE_API_KEY: {{ .Values.claude.apiKey | default "" | quote }}
{{- end }}
{{- if and (not .Values.dbSecret.existingSecret) (ne .Values.db.type "h2") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "claude-toolkit.fullname" . }}-db
  labels:
    {{- include "claude-toolkit.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | default "" | quote }}
{{- end }}
