-- 샘플: 성능 이슈가 있는 Oracle 쿼리 (테스트용)
SELECT *
FROM T_ORDER o,
     T_CUSTOMER c,
     T_PRODUCT p
WHERE o.CUST_ID = c.CUST_ID
AND o.PROD_ID = p.PROD_ID
AND TO_CHAR(o.ORD_DT, 'YYYYMM') = '202401'
AND (SELECT COUNT(*) FROM T_ORDER_DETAIL d WHERE d.ORD_ID = o.ORD_ID) > 0
ORDER BY o.ORD_DT DESC;
